Numpy

In [1]:
import numpy as np

Creating 1D numpy array

In [2]:
array1=np.array([3,6,8,2])
print(array1)

[3 6 8 2]


Creating 2D numpy array

In [4]:
array2=np.array([[1,2,3,4],[6,7,8,9]])
print(array2)

[[1 2 3 4]
 [6 7 8 9]]


Creating 3D numpy array

In [5]:
array3=np.array([[[1,2,3,4],[5,7,1,4],[4,21,23,45]],
                 [[32,21,45,53],[83,37,48,18],[31,48,57,10]]])
print(array3)

[[[ 1  2  3  4]
  [ 5  7  1  4]
  [ 4 21 23 45]]

 [[32 21 45 53]
  [83 37 48 18]
  [31 48 57 10]]]


Size of Numpy Array

In [6]:
print(array1.size)
print(array2.size)
print(array3.size)

4
8
24


Datatype of Numpy Array

In [7]:
print(array1.dtype)
print(array2.dtype)
print(array3.dtype)

int64
int64
int64


Dimensions of Numpy Array

In [8]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


Shape of Numpy Array

In [9]:
print(array1.shape)
print(array2.shape)
print(array3.shape)

(4,)
(2, 4)
(2, 3, 4)


Item Size of Numpy Array

In [10]:
print(array1.itemsize)
print(array2.itemsize)
print(array3.itemsize)

8
8
8


Data attribute of Numpy Array

In [11]:
print(array1.data)
print(array2.data)
print(array3.data)

Array elements using Index

In [15]:
print(array1[0])
print(array2[0][0])
print(array3[0][1][0])

3
1
5


Modify Array Elements Using index

In [20]:
array1[0]=86
array2[0][1]=68
array3[0][1][2]=37
print(array1)
print(array2)
print(array3)

[86  6  8  2]
[[67 68  3  4]
 [ 6  7  8  9]]
[[[37  2  3  4]
  [37  7 37  4]
  [ 4 21 23 45]]

 [[32 21 45 53]
  [83 37 48 18]
  [31 48 57 10]]]


Numpy Statstical Functions

Median

In [21]:
median1=np.median(array1)
median2=np.median(array2)
median3=np.median(array3)
print(median1)
print(median2)
print(median3)

7.0
7.5
31.5


Mean of numpy Array

In [22]:
mean1=np.mean(array1)
mean2=np.mean(array2)
mean3=np.mean(array3)
print(mean1)
print(mean2)
print(mean3)

25.5
21.5
29.458333333333332


Standard Deviation of Numpy Array

In [23]:
std1=np.std(array1)
std2=np.std(array2)
std3=np.std(array3)
print(std1)
print(std2)
print(std3)

34.99642838919423
26.622359023948274
20.599310600654142


Percentile of Numpy Array

In [24]:
percentile1=np.percentile(array1,50)
percentile2=np.percentile(array2,50)
percentile3=np.percentile(array3,50)
print(percentile1)
print(percentile2)
print(percentile3)

7.0
7.5
31.5


Minimum of Numpy Array

In [25]:
min1=np.min(array1)
min2=np.min(array2)
min3=np.min(array3)
print(min1)
print(min2)
print(min3)

2
3
2


Maximum of Numpy Array

In [26]:
max1=np.max(array1)
max2=np.max(array2)
max3=np.max(array3)
print(max1)
print(max2)
print(max3)

86
68
83
