Central Tendancy and Measures of Dispersion

In [ ]:
import numpy as np
from statistics import mean,median,mode
data=[2,4,4,4,5,5,7,9]
print("Mean:",mean(data))
print("Median:",median(data))
print("Mode:",mode(data))
print("Variance:",np.var(data))
print("Standard Deviation:",np.std(data))

Mean: 5
Median: 4.5
Mode: 4
Variance: 4.0
Standard Deviation: 2.0


Number functions

In [ ]:
import math
print(math.ceil(2.3))
print(math.floor(2.7))
print(math.trunc(8.9))

3
2
8


Power and Logarithmic functions

In [ ]:
print(math.pow(2,3))
print(math.sqrt(16))
print(math.exp(2))
print(math.log(100,10))

8.0
4.0
7.38905609893065
2.0


Trigonometric functions

In [ ]:
print(math.sin(math.pi/2))
print(math.cos(0))
print(math.tan(math.pi/4))
print(math.radians(90))
print(math.degrees(math.pi))

1.0
1.0
0.9999999999999999
1.5707963267948966
180.0


Special functions

In [ ]:
print(math.factorial(5))
print(math.gcd(20, 8))
print(math.fabs(-7.5))

120
4
7.5


Constants

In [ ]:
print(math.pi)
print(math.e)

3.141592653589793
2.718281828459045


Scipy

In [ ]:
from scipy import constants
print(constants.pi)
print(constants.yotta)
print(constants.zetta)
print(constants.exa)
print(constants.peta)
print(constants.tera)
print(constants.giga)
print(constants.mega)
print(constants.kilo)
print(constants.hecto)
print(constants.deka)
print(constants.deci)
print(constants.centi)
print(constants.milli)
print(constants.micro)
print(constants.nano)
print(constants.pico)
print(constants.femto)
print(constants.atto)
print(constants.zepto)

3.141592653589793
1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


In [ ]:
print(constants.kibi)
print(constants.mebi)
print(constants.gibi)
print(constants.tebi)
print(constants.pebi)
print(constants.exbi)
print(constants.zebi)
print(constants.yobi)

1024
1048576
1073741824
1099511627776
1125899906842624
1152921504606846976
1180591620717411303424
1208925819614629174706176


In [ ]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix
arr = np.array([
[0, 1, 2],
[1, 0, 0],
[2, 0, 0]
])
newarr = csr_matrix(arr)
print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


Dijkstra

In [ ]:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix
arr = np.array([
[0, 1, 2],
[1, 0, 0],
[2, 0, 0]
])
newarr = csr_matrix(arr)
print(dijkstra(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


In [ ]:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix
arr=np.array([
    [0,1,2],
    [1,0,0],
    [2,0,0]
])
newarr=csr_matrix(arr)
print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [ ]:
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
  [0, -1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0], dtype=int32))
